sudo: required
python: 3.6

language: C

matrix:
  include:
    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - sudo apt-get install valgrind
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - git clone https://github.com/plures/ndtypes.git
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda install --yes conda-build
        - conda update --yes -n base conda
      script:
        - cd ndtypes
        - conda build .conda/libndtypes
        - conda build .conda/ndtypes
        - cd ..
        - conda build .conda
