sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - valgrind

language: C

matrix:
  include:
    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=gcc-4.9
        - cd ndtypes
        - ./configure && make && cd ..
      script:
        - ./configure --with-ndtypes-path=.
        - make check

    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=gcc-4.9
        - cd ndtypes
        - ./configure && make && cd ..
      script:
        - ./configure --with-ndtypes-path=.
        - make memcheck

    - compiler: clang
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - ./configure && make && cd ..
      script:
        - ./configure --with-ndtypes-path=.
        - make check

    - language: objective-c
      os: osx
      compiler: clang
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - ./configure && make && cd ..
      script:
        - ./configure --with-ndtypes-path=.
        - make check

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bison; brew link bison --force; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
