package:
  name: xnd
  version: 0.2.0b2

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

test:
  files:
    - test
  commands:
    - python test/test_xnd.py --long
  requires:
    - libndtypes ==0.2.0b2
    - libxnd ==0.2.0b2
    - ndtypes ==0.2.0b2
    - python >=3.6

requirements:
  build:
    - libndtypes ==0.2.0b2
    - libxnd ==0.2.0b2
    - ndtypes ==0.2.0b2
    - python >=3.6
  run:
    - libndtypes ==0.2.0b2
    - libxnd ==0.2.0b2
    - ndtypes ==0.2.0b2
    - python >=3.6

about:
  home: https://github.com/plures/
  license: BSD 3-clause

source:
  git_url: ../../
